### PR TITLE
[HA] Header and Nav

### PR DESCRIPTION
**Pull request by rubiocanino**
Mobile view:
image

Desktop view:
image

I added some files to have order in the stylesheets.

### CODE REVIEW

**Comment by phavor** [comment]
Yes, something like that. Please do resolve your merge conflicts when you are ready

**Comment by rubiocanino** [comment]
The H1,H2 Corrrected in commit [dace664](https://github.com/HacktoberfestinAba/HacktoberfestinAba.github.io/pull/66/commits/dace664b37d4ab5f9789220e71a29b4a62b5f7ed)

**Comment by phavor** [comment]
Please update your local copy and resolve conflict

**Comment by rubiocanino** [comment]
Thanks! 🤭

**Pull request merged**
